volumes:
  n8n_storage:
    name: n8n_storage
    driver: local
    driver_opts:
      type: none
      device: ./n8n_storage
      o: bind

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=$N8N_HOST
      - N8N_EDITOR_BASE_URL=$N8N_EDITOR_BASE_URL
      - WEBHOOK_URL=$N8N_WEBHOOK_URL
      - GENERIC_TIMEZONE=$GENERIC_TIMEZONE
      - TZ=$TZ
      - N8N_DEFAULT_LOCALE=$N8N_DEFAULT_LOCALE
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - cloudflared_tunnel

  cloudflared:
    container_name: macstudio-cf-tunel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
    networks:
      - cloudflared_tunnel

networks:
  cloudflared_tunnel:
    driver: bridge
